### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by GX77** [MCG-NJU/TRACE#8]
Hi, I'm interested in your work.  Can you publish the trained model parameters?

**Comment by tyshiwo1** [comment]
We have pulished the model weights on VidVRD.
As for AG, we will pulish the model weights after cvpr2022 dead line.

**Comment by GX77** [comment]
ok，thank you.



发自我的iPhone


------------------ Original ------------------
From: yao teng ***@***.***&gt;
Date: Wed,Nov 10,2021 6:44 PM
To: MCG-NJU/TRACE ***@***.***&gt;
Cc: GX77 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MCG-NJU/TRACE] Trained model (Issue #8)

**Comment by tyshiwo1** [comment]
If you still have questions, you may add my wechat: tyshiwo1
