### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by Tangolin** [MCG-NJU/TRACE#9]
Hi, is it possible to release a requirements.txt with version for each library? I am currently trying to build Detectron and I have been running into this error:
```File "/home/siteng/anaconda3/envs/test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/siteng/anaconda3/envs/test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/siteng/anaconda3/envs/test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

I am speculating that there may be some kind of compatibility issue. Thank you!

**Comment by Tangolin** [comment]
If I can also ask, which version of python were you using?

**Comment by tyshiwo1** [comment]
I find python 3.8 is ok.

**Comment by tyshiwo1** [comment]
my cuda version is 10.1

**Comment by Tangolin** [comment]
I am currently using the same set up as you but for some reason I am getting this error. I am currently trying to use TRACE as a component for the model I am developing, is it possible to release the outputs of TRACE on the Action Genome dataset directly then?

**Comment by tyshiwo1** [comment]
can you give your wechat through e-mail? my e-mail: ty1234567@126.com

may be i can give what you want through it
